[project]
name = "det_research_workspace"
version = "0.1.0"
description = ""
authors = [{ name = "Mick", email = "cartemic@proton.me" }]
readme = "README.md"
classifiers = ["Private :: Do not Upload"]
requires-python = ">=3.13,<3.14"
dependencies = [
    "file_utils",
    "funcs",
    "sdtoolbox",
]

[tool.uv.sources]
file_utils = { workspace = true }
funcs = { workspace = true }
sdtoolbox = { workspace = true }

[tool.uv.workspace]
members = [
    "file_utils",
    "funcs",
    "sdtoolbox",
    "scripts/perturbation_study",
    "scripts/measurement_paper",
    "scripts/final_manuscript",
]

[tool.ruff]
line-length = 120
extend-exclude = ["sdtoolbox", "sd_matlab_test", "*.ipynb"]
lint.select = [
    "A", # Prevent builtin shadowing
    #    "ANN",  # Check for missing type annotations and `typing.Any`
    "ARG",    # Check for unused args
    "C4",     # flake8-comprehension checks
    "COM818", # Comma police, arrest this man
    "COM819", # He talks in maths, he buzzes like a fridge
    "E",      # Check for syntax errors
    "ERA",    # Prevent commented-out code
    "F",      # Pyflakes
    "I",      # Isort
    "ISC", # Avoid string concatenation goofs
    "N",      # Enforce pep8 naming conventions
    "NPY",    # Numpy-specific lints
    "PD",     # Pandas-specific lints
    "PERF",   # Perormance-conscious lints
    "PIE",    # Checks for unnecessary placeholders, duplicate enum values, unnecessary spreads, etc.
    "PL",     # Pylint checks
    "Q",      # Flake8 quote checks
    "RET",    # Make sure returns are excellent
    "RUF",    # Apply ruff-specific rules
    "S101",   # Keep `assert` out of production code
    "S102",   # Avoid abritrary code execution via `exec()`
    "SIM",    # Check for simplifications
    "SLF",    # Avoid private member access
    "TID",    # Keep imports tidy
    "TRY002", # Avoid `Exception`, `BaseException`
    "TRY300", # Avoid returns in try blocks
    "TRY400", # Prefer `logging.exception` to `logging.error` for traceback preservation
    "W",      # Code style warnings

]
lint.ignore = [
    "COM812",  # Trailing comma enforcement, which runs afoul of the formatter on occasion
    "RET504",  # Allow unnecessary assignment before return, which can make debugging nicer
    "RET505",  # Allow early returns
    "ERA001",  # todo: temporarily allow commented-out code :(
    "PLR0913", # todo: temporarily allow piles of function arguments
    "ANN10",   # Allow untyped `self`, `cls`
    "PD002",   # Not worth removing inplace at this point
    "PLR0915", # Not worth refactoring long things at this point
    "PLR0912", # Same goes for overly branched things
    "PD008",   # Allow DataFrame.at()
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402", # Allow interesting imports in __init__, e.g. for version checks
    "F401", # Unused imports can be used to define the shape of the API and are therefore okay in __init__
]
"**/test_*.py" = [
    "S101",    # Allow `assert` in tests
    "PLR2004", # Allow direct comparison with values in tests
    "SLF001",  # Allow private member access in tests
]
