[project]
name = "final-manuscript"
version = "0.1.0"
requires-python = "==3.13.*"
dependencies = [
    "cantera>=3.1.0",
    "file-utils",
    "funcs",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pyqt5>=5.15.11",
    "rich>=14.1.0",
    "sdtoolbox",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "typer>=0.16.1",
    "uncertainties>=3.2.3",
]

[tool.uv.sources]
funcs = { workspace = true }
sdtoolbox = { workspace = true }
file-utils = { workspace = true }
