[project]
name = "perturbation-study"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "funcs",
    "file_utils",
    "matplotlib>=3.10.5",
    "pandera[pandas]>=0.24.0",
    "psycopg>=3.2.9",
    "pypbomb",
    "scipy>=1.16.1",
    "sdtoolbox",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "typer>=0.16.1",
]

[tool.uv.sources]
file_utils = { workspace = true }
funcs = { workspace = true }
sdtoolbox = { workspace = true }
pypbomb = { path="../../../pypbomb" }

[dependency-groups]
eda = [
    "jupyterlab>=4.4.6",
]
