# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(404, 378)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 386, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutVertMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutVertMain.setContentsMargins(0, 0, 0, 0)
        self.layoutVertMain.setObjectName("layoutVertMain")
        self.btnLoadHDF5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLoadHDF5.setMinimumSize(QtCore.QSize(0, 25))
        self.btnLoadHDF5.setBaseSize(QtCore.QSize(0, 25))
        self.btnLoadHDF5.setObjectName("btnLoadHDF5")
        self.layoutVertMain.addWidget(self.btnLoadHDF5)
        self.layoutFormSelectDate = QtWidgets.QFormLayout()
        self.layoutFormSelectDate.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.layoutFormSelectDate.setObjectName("layoutFormSelectDate")
        self.cboxSelectDate = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cboxSelectDate.setMinimumSize(QtCore.QSize(240, 0))
        self.cboxSelectDate.setObjectName("cboxSelectDate")
        self.layoutFormSelectDate.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cboxSelectDate)
        self.lblSelectDate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblSelectDate.setObjectName("lblSelectDate")
        self.layoutFormSelectDate.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblSelectDate)
        self.layoutVertMain.addLayout(self.layoutFormSelectDate)
        self.layoutHorizShotSelect = QtWidgets.QHBoxLayout()
        self.layoutHorizShotSelect.setObjectName("layoutHorizShotSelect")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutHorizShotSelect.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.inpStartShot = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.inpStartShot.setEnabled(False)
        self.inpStartShot.setMinimumSize(QtCore.QSize(50, 25))
        self.inpStartShot.setMaximumSize(QtCore.QSize(50, 25))
        self.inpStartShot.setAlignment(QtCore.Qt.AlignCenter)
        self.inpStartShot.setObjectName("inpStartShot")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inpStartShot)
        self.lblStartShot = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblStartShot.setObjectName("lblStartShot")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblStartShot)
        self.layoutHorizShotSelect.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lblEndShot = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblEndShot.setObjectName("lblEndShot")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblEndShot)
        self.inpEndShot = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.inpEndShot.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inpEndShot.sizePolicy().hasHeightForWidth())
        self.inpEndShot.setSizePolicy(sizePolicy)
        self.inpEndShot.setMinimumSize(QtCore.QSize(50, 25))
        self.inpEndShot.setMaximumSize(QtCore.QSize(50, 25))
        self.inpEndShot.setBaseSize(QtCore.QSize(0, 0))
        self.inpEndShot.setAlignment(QtCore.Qt.AlignCenter)
        self.inpEndShot.setObjectName("inpEndShot")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inpEndShot)
        self.layoutHorizShotSelect.addLayout(self.formLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutHorizShotSelect.addItem(spacerItem1)
        self.layoutVertMain.addLayout(self.layoutHorizShotSelect)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblStoredCalibrations = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblStoredCalibrations.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStoredCalibrations.setObjectName("lblStoredCalibrations")
        self.verticalLayout.addWidget(self.lblStoredCalibrations)
        self.layoutHorizStoredSpatials = QtWidgets.QHBoxLayout()
        self.layoutHorizStoredSpatials.setObjectName("layoutHorizStoredSpatials")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutHorizStoredSpatials.addItem(spacerItem2)
        self.chkStoredNear = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkStoredNear.setCheckable(True)
        self.chkStoredNear.setObjectName("chkStoredNear")
        self.layoutHorizStoredSpatials.addWidget(self.chkStoredNear)
        self.chkStoredFar = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkStoredFar.setCheckable(True)
        self.chkStoredFar.setObjectName("chkStoredFar")
        self.layoutHorizStoredSpatials.addWidget(self.chkStoredFar)
        self.chkStoredCenterline = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkStoredCenterline.setCheckable(True)
        self.chkStoredCenterline.setObjectName("chkStoredCenterline")
        self.layoutHorizStoredSpatials.addWidget(self.chkStoredCenterline)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutHorizStoredSpatials.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.layoutHorizStoredSpatials)
        self.layoutVertMain.addLayout(self.verticalLayout)
        self.layoutFormSelectSpatialLocation = QtWidgets.QFormLayout()
        self.layoutFormSelectSpatialLocation.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.layoutFormSelectSpatialLocation.setObjectName("layoutFormSelectSpatialLocation")
        self.lblSelectSpatialLocation = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblSelectSpatialLocation.setObjectName("lblSelectSpatialLocation")
        self.layoutFormSelectSpatialLocation.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblSelectSpatialLocation)
        self.cboxSelectLocation = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cboxSelectLocation.setMinimumSize(QtCore.QSize(240, 0))
        self.cboxSelectLocation.setObjectName("cboxSelectLocation")
        self.cboxSelectLocation.addItem("")
        self.cboxSelectLocation.addItem("")
        self.layoutFormSelectSpatialLocation.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cboxSelectLocation)
        self.layoutVertMain.addLayout(self.layoutFormSelectSpatialLocation)
        self.btnLoadAndCalibrate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLoadAndCalibrate.setEnabled(False)
        self.btnLoadAndCalibrate.setMinimumSize(QtCore.QSize(0, 25))
        self.btnLoadAndCalibrate.setBaseSize(QtCore.QSize(0, 25))
        self.btnLoadAndCalibrate.setObjectName("btnLoadAndCalibrate")
        self.layoutVertMain.addWidget(self.btnLoadAndCalibrate)
        self.btnStoreCalibration = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStoreCalibration.setEnabled(False)
        self.btnStoreCalibration.setMinimumSize(QtCore.QSize(0, 25))
        self.btnStoreCalibration.setBaseSize(QtCore.QSize(0, 25))
        self.btnStoreCalibration.setObjectName("btnStoreCalibration")
        self.layoutVertMain.addWidget(self.btnStoreCalibration)
        self.btnExit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnExit.setMinimumSize(QtCore.QSize(0, 100))
        self.btnExit.setBaseSize(QtCore.QSize(0, 50))
        self.btnExit.setObjectName("btnExit")
        self.layoutVertMain.addWidget(self.btnExit)
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Schlieren Spatial Calibration"))
        self.btnLoadHDF5.setText(_translate("MainWindow", "Load Schlieren HDF5"))
        self.lblSelectDate.setText(_translate("MainWindow", "Select Date"))
        self.lblStartShot.setText(_translate("MainWindow", "Start Shot"))
        self.lblEndShot.setText(_translate("MainWindow", "End Shot"))
        self.lblStoredCalibrations.setText(_translate("MainWindow", "Stored Spatial Calibrations"))
        self.chkStoredNear.setText(_translate("MainWindow", "Near"))
        self.chkStoredFar.setText(_translate("MainWindow", "Far"))
        self.chkStoredCenterline.setText(_translate("MainWindow", "Centerline"))
        self.lblSelectSpatialLocation.setText(_translate("MainWindow", "Select Spatial Location"))
        self.cboxSelectLocation.setItemText(0, _translate("MainWindow", "Near"))
        self.cboxSelectLocation.setItemText(1, _translate("MainWindow", "Far"))
        self.btnLoadAndCalibrate.setText(_translate("MainWindow", "Load Spatial and Perform Calibration"))
        self.btnStoreCalibration.setText(_translate("MainWindow", "Store Calibration"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))

